/home/efleisig/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/efleisig/sams_reu/llama3_train.py", line 19, in <module>
    max_token_id = max([max(ex) for ex in dataset['input_ids']])
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2861, in __getitem__
    return self._getitem(key)
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2845, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 584, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 521, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column input_ids not in the dataset. Current columns in the dataset: ['text']"
Traceback (most recent call last):
  File "/home/efleisig/sams_reu/llama3_train.py", line 19, in <module>
    max_token_id = max([max(ex) for ex in dataset['input_ids']])
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2861, in __getitem__
    return self._getitem(key)
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2845, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 584, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/efleisig/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 521, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column input_ids not in the dataset. Current columns in the dataset: ['text']"